### ISSUE TITLE
`test_chainbuilder.test_arm_func_call` failing intermittently in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angrop#115]
### Description

```
2024-07-22T17:53:27.5548253Z ======================================================================
2024-07-22T17:53:27.5549064Z ERROR: test_chainbuilder.test_arm_func_call
2024-07-22T17:53:27.5550150Z ----------------------------------------------------------------------
2024-07-22T17:53:27.5551047Z Traceback (most recent call last):
2024-07-22T17:53:27.5552095Z   File "/__w/cle/cle/build/src/angrop/tests/test_chainbuilder.py", line 52, in test_arm_func_call
2024-07-22T17:53:27.5553549Z     state = chain1.exec()
2024-07-22T17:53:27.5554471Z   File "/__w/cle/cle/build/src/angrop/angrop/rop_chain.py", line 249, in exec
2024-07-22T17:53:27.5555680Z     return rop_utils.step_to_unconstrained_successor(self._p, state, max_steps=max_steps,
2024-07-22T17:53:27.5557169Z   File "/__w/cle/cle/build/src/angrop/angrop/rop_utils.py", line 301, in step_to_unconstrained_successor
2024-07-22T17:53:27.5558940Z     return step_to_unconstrained_successor(project, succ.flat_successors[0], max_steps=max_steps-1,
2024-07-22T17:53:27.5560524Z   File "/__w/cle/cle/build/src/angrop/angrop/rop_utils.py", line 301, in step_to_unconstrained_successor
2024-07-22T17:53:27.5562232Z     return step_to_unconstrained_successor(project, succ.flat_successors[0], max_steps=max_steps-1,
2024-07-22T17:53:27.5564085Z   File "/__w/cle/cle/build/src/angrop/angrop/rop_utils.py", line 301, in step_to_unconstrained_successor
2024-07-22T17:53:27.5566042Z     return step_to_unconstrained_successor(project, succ.flat_successors[0], max_steps=max_steps-1,
2024-07-22T17:53:27.5567055Z   [Previous line repeated 5 more times]
2024-07-22T17:53:27.5568298Z   File "/__w/cle/cle/build/src/angrop/angrop/rop_utils.py", line 306, in step_to_unconstrained_successor
2024-07-22T17:53:27.5569633Z     raise RopException("Does not get to an unconstrained successor")
2024-07-22T17:53:27.5570716Z angrop.errors.RopException: Does not get to an unconstrained successor
```

### Environment

CI

**Comment by Kyle-Kyle** [comment]
should be fixed in the latest PR
