### ISSUE TITLE
AttributeError: 'SimSolver' object has no attribute 'BVV'

### ISSUE THREAD

**Issue by gr0grig** [angr/angrop#118]
### Question

Guys, what am I doing wrong? The code from the example gives an error.

```python
import angr, angrop
p = angr.Project("/bin/ls")
rop = p.analyses.ROP()
rop.find_gadgets()

'''
AttributeError: 'SimSolver' object has no attribute 'BVV'
'SimSolver' object has no attribute 'BVV'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/angrop/gadget_finder/gadget_analyzer.py", line 62, in analyze_gadget
    ctrl_type = self._check_for_control_type(init_state, final_state)
  File "/home/user/.local/lib/python3.10/site-packages/angrop/gadget_finder/gadget_analyzer.py", line 425, in _check_for_control_type
    if self._check_if_stack_controls_ast(ip, init_state):
  File "/home/user/.local/lib/python3.10/site-packages/angrop/gadget_finder/gadget_analyzer.py", line 508, in _check_if_stack_controls_ast
    concrete_stack = initial_state.solver.BVV(b"B" * stack_bytes_length)
AttributeError: 'SimSolver' object has no attribute 'BVV'
'''
```

**Comment by twizmwazin** [comment]
This is due to a change I made recently in angr. The version on master works if you can install from git. I’ll see about getting a release published shortly so that the pypi version works again.

**Comment by gr0grig** [comment]
Thx for the answer, pal

**Comment by twizmwazin** [comment]
Just posted a new release of angrop to pypi, so this should be fixed!
