### ISSUE TITLE
`test_rop_i386_cgc` timeout in CI

### ISSUE THREAD

**Issue by mborgerson** [angr/angrop#38]
angr CI, test_rop_i386_cgc will fail about 20% of the time and takes >2 minutes to run.

![image](https://user-images.githubusercontent.com/8210/141033925-03204dde-8090-4a62-b7ff-f7a3c17f2dc6.png)

---
Interestingly nearby gadgets are found, but the target gadget is not.

```
======================================================================
FAIL: test_rop.test_rop_i386_cgc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/1/s/build/src/angrop/tests/test_rop.py", line 133, in test_rop_i386_cgc
    compare_gadgets(rop.gadgets, test_gadgets)
  File "/__w/1/s/build/src/angrop/tests/test_rop.py", line 79, in compare_gadgets
    nose.tools.assert_in(g.addr, found_addrs)
AssertionError: 134513864 not found in {134513692, 134513696, 134513697, 134513698, 134513699, 134513700, 134513701, 134513702, 134513704, 134513705, 134513706, 134513707, 134513716, 134513718, 134513720, 134513722, 134513724, 134513725, 134513727, 134513729, 134513731, 134513732, 134513744, 134513746, 134513748, 134513750, 134513751, 134513752, 134513754, 134513756, 134513757, 134513758, 134513759, 134513760, 134513761, 134513762, 134513763, 134513764, 134513776, 134513778, 134513780, 134513782, 134513783, 134513784, 134513786, 134513788, 134513789, 134513790, 134513791, 134513792, 134513793, 134513794, 134513795, 134513796, 134513813, 134513814, 134513815, 134513816, 134513817, 134513819, 134513821, 134513823, 134513825, 134513826, 134513827, 134513828, 134513829, 134513830, 134513831, 134513832, 134513833, 134513834, 134513839, 134513840, 134513841, 134513842, 134513843, 134513845, 134513846, 134513847, 134513849, 134513850, 134513851, 134513852, 134513853, 134513854, 134513855, 134513856, 134513857, 134513858, 134513859, 134513860, 134513861, 134513862, 134513863, 134513865, 134513866, 134513867, 134513868, 134513870, 134513872, 134513874, 134513876, 134513878, 134513879, 134513880, 134513885, 134513886, 134513887, 134513888, 134513889, 134513891, 134513892, 134513893, 134513895, 134513896, 134513897, 134513898, 134513899, 134513900, 134513901, 134513902, 134513903, 134513904, 134513905, 134513906, 134513919, 134513921, 134513922, 134513925, 134513927, 134513928, 134513931, 134513933, 134513962, 134513965, 134513967, 134513471, 134513472, 134513473, 134513476, 134513477, 134513478, 134513479, 134513480, 134513481, 134513482, 134513484, 134513485, 134513486, 134513487, 134513488, 134513489, 134513490, 134513031, 134513032, 134513034, 134513036, 134513038, 134513039, 134513040}

-------------------- >> begin captured stdout << ---------------------
[angrop] Timeout

```

**Comment by mborgerson** [comment]
pinned

**Comment by twizmwazin** [comment]
Is this issue still valid? Since switching to actions we don't have a long-term tracker, but it hasn't been the cause of a failure so far. It is possible that performance improvements in angr and z3 have effectively solved this.

**Comment by Kyle-Kyle** [comment]
Is this still failing? I can look into it.

**Comment by twizmwazin** [comment]
I think this has been fixed. Nightly CI has been passing consistently for a while.
