### ISSUE TITLE
rop.func_call() bug in ARM

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#86]
### Description

As of this [commit](https://github.com/angr/angrop/commit/1a0b0fdb3d7d1b66df8793a339df9d0da42d598c), func_call in arm is misbehaving. 
Prior to that commit, func_call was working as expected. After the commit, we get a RopException error.
The attached example produces the below output.

```
This is the GOOD example
WARNING  | 2024-02-21 17:15:00,623 | cle.backends.elf.relocation | Unknown reloc 160 on ARMEL
WARNING  | 2024-02-21 17:15:00,743 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __libc_enable_secure
WARNING  | 2024-02-21 17:15:00,743 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __pointer_chk_guard
WARNING  | 2024-02-21 17:15:00,743 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __stack_chk_guard
WARNING  | 2024-02-21 17:15:00,743 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _dl_argv
WARNING  | 2024-02-21 17:15:00,745 | cle.loader     | For more information about "Symbol was allocated without a known size",see https://docs.angr.io/extending-angr/environment#simdata
WARNING  | 2024-02-21 17:15:00,746 | angr.project   | Address is already hooked, during hook(0x500520, <SimProcedure __tls_get_addr>). Not re-hooking.
ERROR    | 2024-02-21 17:15:00,746 | angr.simos.linux | KeyError while trying to set up rtld_global. Libc emulation may not work.
WARNING  | 2024-02-21 17:15:00,747 | angrop.rop     | rebase is deprecated in angrop!
WARNING  | 2024-02-21 17:15:00,747 | angrop.gadget_finder | Only have syscall strings for i386 and x86_64
ROP: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 237851/237851 [02:33<00:00, 1544.78it/s]
code_base = 0x0
chain = b""
chain += p32(code_base + 0x5edfc)	# pop {r0, r4, pc}
chain += p32(0xcafebabe)
chain += p32(0x0)
chain += p32(code_base + 0x1a5cc)




This is the BAD example
WARNING  | 2024-02-21 17:17:38,999 | cle.backends.elf.relocation | Unknown reloc 160 on ARMEL
WARNING  | 2024-02-21 17:17:39,114 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __libc_enable_secure
WARNING  | 2024-02-21 17:17:39,114 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __pointer_chk_guard
WARNING  | 2024-02-21 17:17:39,114 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __stack_chk_guard
WARNING  | 2024-02-21 17:17:39,114 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _dl_argv
WARNING  | 2024-02-21 17:17:39,116 | cle.loader     | For more information about "Symbol was allocated without a known size",see https://docs.angr.io/extending-angr/environment#simdata
WARNING  | 2024-02-21 17:17:39,117 | angr.project   | Address is already hooked, during hook(0x500520, <SimProcedure __tls_get_addr>). Not re-hooking.
ERROR    | 2024-02-21 17:17:39,117 | angr.simos.linux | KeyError while trying to set up rtld_global. Libc emulation may not work.
WARNING  | 2024-02-21 17:17:39,118 | angrop.rop     | rebase is deprecated in angrop!
WARNING  | 2024-02-21 17:17:39,118 | angrop.gadget_finder | Only have syscall strings for i386 and x86_64
ROP: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 237851/237851 [02:33<00:00, 1545.22it/s]
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    chain1 = rop.func_call("free", [0xcafebabe])
  File ".venv_bad/lib/python3.10/site-packages/angrop/chain_builder/__init__.py", line 110, in func_call
    return self._func_caller.func_call(address, args, **kwargs)
  File ".venv_bad/lib/python3.10/site-packages/angrop/chain_builder/func_caller.py", line 104, in func_call
    return self._func_call(func_gadget, cc, args, **kwargs)
  File ".venv_bad/lib/python3.10/site-packages/angrop/chain_builder/func_caller.py", line 73, in _func_call
    shifter = self.chain_builder._shifter.shift(self.project.arch.bytes)
  File ".venv_bad/lib/python3.10/site-packages/angrop/chain_builder/shifter.py", line 71, in shift
    raise RopException("Encounter a shifting request that requires chaining multiple shifting gadgets" +
angrop.errors.RopException: Encounter a shifting request that requires chaining multiple shifting gadgetstogether which is not support atm. Plz create an issue on GitHub so we can add the support!
```

### Steps to reproduce the bug

Attahced is a zip file. Unzip and run start.sh. This will make two venv. One for the latest angrop commit in main, and one at commit 1a0b0fd. It will analyze libc for arm and try to produce the following chain:

```
chain1 = rop.func_call("free", [0xcafebabe])
```

The one at commit 1a0b0fd will succeed, the one at the latest commit will fail.

[angrop_arm_func_call_issue.zip](https://github.com/angr/angrop/files/14366028/angrop_arm_func_call_issue.zip)

**Comment by Kyle-Kyle** [comment]
Let me explain the fix first, you can fix this issue by adding the `is_thumb=True` flag to the analysis and then the test case will pass. This is because the library is mostly written in thumb mode, so it has way more thumb mode gadgets in it.

But why it requires more gadgets now? This is because to fix https://github.com/angr/angrop/issues/79, we need to handle the LR register, which requires more gadgets.
I'm pretty sure if you explicitly mark it with `needs_return=False`, the test case will pass as well.

**Comment by astewart-bah** [comment]
@Kyle-Kyle 
Both seem to fix the issue. Thank you very much!

Closing the issue.
